version: "3.3"

services:
  bot_server:
    hostname: 'bot_server'
    image: ghcr.io/lukaszraczylo/tdlib-telegram-bot-api-docker/telegram-api-server:api-5.3.2
    restart: unless-stopped
    env_file:
      - .env
    command: [ "--local", "--dir", "/srv/public"]
    volumes:
      - ./bot_server_volume:/srv/public

  bot:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - "mongo"
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - RUN_IN_DOCKER=true
    volumes:
      - ./bot_server_volume:/raindropiobot/public

  mongo:
    hostname: 'mongo'
    image: mongo:4.4
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mongo_volume:/data/db