FROM python:3.9

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/app"
COPY . /app/

CMD ["uvicorn", "htmlshare:app", "--host", "0.0.0.0", "--port", "80"]
